_target_: pytorch_lightning.Trainer
default_root_dir: ${paths.output_dir}
min_epochs: 1
max_epochs: 1
accelerator: gpu
devices: [0,1,2,3,4,5,6,7] # 如需多卡: [0,1,2,3]
strategy: ddp # 多卡时改为 ddp
precision: 16-mixed # 混合精度
gradient_clip_val: 1.0
log_every_n_steps: 50
check_val_every_n_epoch: 1
num_sanity_val_steps: 2